apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
type: Opaque
stringData:
  POSTGRES_USER: <<anonymized>>
  POSTGRES_PASSWORD: <<anonymized>>
  POSTGRES_DB: devdb
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 4Gi
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: initdb-config
data:
  schema.sql: |
    CREATE EXTENSION vector;
       
    CREATE TABLE IF NOT EXISTS project (
        id BIGSERIAL PRIMARY KEY,
        ext_id UUID NOT NULL UNIQUE,
        name VARCHAR(50) NOT NULL,
        created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
        user_id UUID NOT NULL,
        description VARCHAR(255),
        start_date DATE DEFAULT CURRENT_DATE,
        end_date DATE,
        capture_start TIME,
        capture_end TIME,
        UNIQUE (name, user_id)
    );
        
    CREATE TYPE video_state AS ENUM ('QUEUED', 'PROCESSING', 'FINISHED'); 
        
    CREATE CAST ( CHARACTER VARYING as video_state ) WITH INOUT AS IMPLICIT;
    
    CREATE TABLE IF NOT EXISTS video (
        id BIGSERIAL PRIMARY KEY,
        ext_id UUID NOT NULL UNIQUE,
        user_id UUID NOT NULL,
        project_id UUID NOT NULL,
        created_at TIMESTAMP WITH TIME ZONE,
        status video_state NOT NULL DEFAULT 'QUEUED'
    );
    
    CREATE TABLE IF NOT EXISTS picture_embedding (
       project_id BIGSERIAL,
       picture_uuid UUID PRIMARY KEY,
       embedding vector(768),
       extracted_timestamp TIMESTAMP WITH TIME ZONE DEFAULT now()
    );
    ALTER TABLE picture_embedding ADD COLUMN IF NOT EXISTS extracted_timestamp TIMESTAMP WITH TIME ZONE DEFAULT now();

    CREATE TABLE IF NOT EXISTS telemetry (
       id BIGSERIAL PRIMARY KEY,
       project_id UUID,
       timestamp TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
       name TEXT,
       model TEXT,
       is_charging BOOLEAN,
       battery_percentage INT,
       mem_used INT,
       upload_duration INT,
       FOREIGN KEY (project_id) REFERENCES project (ext_id) ON DELETE CASCADE
    );
    -- Add more schema definitions here
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
spec:
  type: ClusterIP
  selector:
    app: postgres
  ports:
    - port: 5432
      targetPort: 5432
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: pgvector/pgvector:pg15
          ports:
            - containerPort: 5432
          envFrom:
            - secretRef:
                name: postgres-secret
          volumeMounts:
            - name: pgdata
              mountPath: /var/lib/postgresql/data
            - name: initdb-scripts
              mountPath: /docker-entrypoint-initdb.d
      volumes:
        - name: pgdata
          persistentVolumeClaim:
            claimName: postgres-pvc
        - name: initdb-scripts
          configMap:
            name: initdb-config
