apiVersion: apps/v1
kind: Deployment
metadata:
  name: timelapse-export
spec:
  replicas: 3
  selector:
    matchLabels:
      app: timelapse-export
  template:
    metadata:
      labels:
        app: timelapse-export
    spec:
      containers:
        - name: timelapse-export
          image: {{fqdn}}/timelapse-export:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 5000
          env:
            - name: MINIO_ENDPOINT
              value: "minio:9000"
          envFrom:
            - secretRef:
                name: minio-secret
---
apiVersion: v1
kind: Service
metadata:
  name: timelapse-export
spec:
  selector:
    app: timelapse-export
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
